server:
  url: jdbc:postgresql://postgres:5432/usersdb

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/usersdb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

